version: '3.8'
services:
  sql-injection-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: injection_db
    ports:
      - "3307:3306"
    volumes:
      - ./sql-injection-app/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  sql-injection-app:
    build: ./sql-injection-app
    depends_on:
      - sql-injection-db
    ports:
      - "8081:8080"